### ISSUE TITLE
where would you like to get dinner?

### ISSUE THREAD

**Issue by calebgregory** [petergaultney/eldrow#1]
?

**Comment by petergaultney** [comment]
hmmmm. 

i am not strongly opinionated about this. I've generally enjoyed the things you've suggested in the past, which have the advantage of being new to me.

**Comment by calebgregory** [comment]
right on... i'll think about a good spot, then...  i am currently very close to Sunflower Cafe, which is a lovely spot.

**Comment by petergaultney** [comment]
you're also pretty close to Baja Burrito, which is a favorite of mine. But I'm open to 🌻 !

**Comment by calebgregory** [comment]
between the two i'm a sunflower fan. we could do a combo situation -- if you wanted baja, you could pick it up and bring it to the sunflower porch

**Comment by petergaultney** [comment]
no no, i'll eat what you eat, etc.

**Comment by petergaultney** [comment]
tested and merged.
